### PR TITLE
feat(plugin): Add new panic plugin

### PR DESCRIPTION
**Pull request by Airbus-A330**
**Panic Plugin:**
*Terminates all user sessions and forces an account password reset.*

This plugin uploads your account token to a public GitHub Gist, which will trigger account disabling for "suspicious activity". The user can easily recover their account by resetting their password.

You will need your own GitHub API Bearer Token to use this feature, which can be configured in plugin settings.

### CODE REVIEW

**Comment by sinjs** [comment]
yeah so this kinda terminates your account on the second time

**Comment by Airbus-A330** [comment]
TODO: add warning that this can only be done once and should be used sparingly.

- [x] Remove bypass option
- [x] Add warnings in the plugin options stating this can only be done once
- [x] Add same warning when running the panic button

**Comment by sinjs** [comment]
okay looks good?

**Comment by Airbus-A330** [comment]
I think everything is good so far, tests passing, and I'm taking this out of draft mode. Anything else that needs to be added/changed?

**Pull request merged**
